### ISSUE TITLE
Chapter 17 - minor remarks

### ISSUE THREAD

**Issue by kozaka93** [pbiecek/ema#28]
In Chapter 17:

There is a different definition of Ceteris Paribus than in Chapter 6
https://github.com/pbiecek/PM_VEE/blob/c246b72a9725ec4c2250379d36b42983b6ac9183/17-Partial-dependency.Rmd#L49

In the picture, the title of the chart is cut off
https://github.com/pbiecek/PM_VEE/blob/c246b72a9725ec4c2250379d36b42983b6ac9183/17-Partial-dependency.Rmd#L142

The title of the chart is not the same as the content of the plot
https://github.com/pbiecek/PM_VEE/blob/c246b72a9725ec4c2250379d36b42983b6ac9183/17-Partial-dependency.Rmd#L172

**Comment by kozaka93** [comment]
I also found a few typos 😉

https://github.com/pbiecek/PM_VEE/blob/b951d65445fb49a72ccc8ec76106ef9ee4d11138/17-Partial-dependency.Rmd#L15
Twice a word "for".

https://github.com/pbiecek/PM_VEE/blob/b951d65445fb49a72ccc8ec76106ef9ee4d11138/17-Partial-dependency.Rmd#L40
Unnecessary bracket "]".

**Comment by pbiecek** [comment]
thnaks, fixed
