### ISSUE TITLE
code to plot titanic ceteric paribus

### ISSUE THREAD

**Issue by asheetal** [pbiecek/ema#31]
I am tryign to follow the tutorial on ceteris paribus. Is there a code on how to plot the diagram on Figure 7.1(A) titanic_lmr_v6
https://pbiecek.github.io/PM_VEE/ceterisParibus.html

**Comment by pbiecek** [comment]
The code for this figure is here:
https://github.com/pbiecek/ema/blob/master/10-Ceteris-paribus-Profiles.Rmd#L35
