### ISSUE TITLE
Grouped partial-dependence profiles does not work with dummy variables

### ISSUE THREAD

**Issue by velf** [pbiecek/ema#43]
Hi, 
I was trying to use **Grouped partial-dependence profiles**  `model_profile()` function in **python**, but unfortunately, it cannot handle as grouping variables floats/integers. The problem is that most RF/Logit models cannot handle text data, therefore variables need to encoded as integers (eg: out of the variable _gender_, I create _gender_female_ with values 0,1). So when I try to apply your aggregated function, I keep getting this error:

`sequence item 0: expected str instance, int found`

Can you transform variables with n<10 categories into strings to be able to get aggregated results for categorical variables? Or just allow integers if for example n_cat<10? 

Thanks!

PS; Cool library!

**Comment by hbaniecki** [comment]
Hi, 
Could you provide any code example?

**Comment by hbaniecki** [comment]
This should be fixed in dalex v0.2.2

**Comment by pbiecek** [comment]
thanks!

**Comment by velf** [comment]
Thanks!

> Hi,
> Could you provide any code example?

Of the error or the input or suggested solution? Do you still need that?

**Comment by hbaniecki** [comment]
@velf you can check if the error is fixed for your usecase on the new version (`pip install dalex -U`)

**Comment by pbiecek** [comment]
thanks for the fix

**Comment by velf** [comment]
Thanks!

Przemysław Biecek <notifications@github.com> ezt írta (időpont: 2021. márc.
4., Cs, 22:01):
