### ISSUE TITLE
Figure 9.5 and 9.8 are not correct

### ISSUE THREAD

**Issue by FrieseWoudloper** [pbiecek/ema#46]
Figure 9.5 and 9.8 are not correct because of [a bug in `localModel`](https://github.com/ModelOriented/localModel/issues/37).

When I apply the workaround as described in the issue, I get a LIME explanation for Johnny D's prediction from the random forest model that is much more intuitive and consistent with the other explanations for the same prediction.

![ex17-1](https://user-images.githubusercontent.com/4244169/103652978-2752e500-4f64-11eb-9f19-9b8140304512.png)

**Comment by FrieseWoudloper** [comment]
I have further investigated the problem. The cause  of the problem is that the ordering of columns in `titanic_imputed` (and thus the dataframe containing the instances in the explainer) is different from that in `johnny_d`. I created a pull request to solve this issue: https://github.com/ModelOriented/localModel/pull/38. Of course a workaround would be to make sure that the column ordering in `johnny_d` is the same as in `titanic_imputed`. 

```
  johnny_d <- DALEX::titanic_imputed[0, -8]
  johnny_d[1, ] <- c("male", 8, "1st", "Southampton", 72, 0, 0)
```

**Comment by pbiecek** [comment]
@FrieseWoudloper thank you for pointing out this issue

**Comment by pbiecek** [comment]
Thank you, it has much more sense now!
