### ISSUE TITLE
predict_surrogate has been moved to DALEXtra

### ISSUE THREAD

**Issue by FrieseWoudloper** [pbiecek/ema#50]
This sentence in https://github.com/pbiecek/ema/blob/master/09-LIME.Rmd 

> Thus, we will use the `predict_surrogate()` method from the `localModel` package.

is not correct. `predict_surrogate()` has been moved to the `DALEXtra` package.

**Comment by pbiecek** [comment]
thank you, fixed in http://ema.drwhy.ai/LIME.html
