### ISSUE TITLE
Improvement in Chapter 6.3 - Break down method

### ISSUE THREAD

**Issue by CriticalNameError** [pbiecek/ema#63]
Hello,

I'd like to suggest a little improvement in chapter 6.3

After the last equal sign in formula (6.2) there is an underline under x star missing I think in f(x_*).

Best regards!

**Comment by pbiecek** [comment]
Hi @CriticalNameError, thank you for spotting this place.

It is actually correct, 
the underline is used to mark the fact that given object is an vector,
so $x$ and $x_*$ are vectors and this is why they have underline. Even $x^{j|=k}$ is a vector with changed j-th coordinate.

But $x^j$ is an i-th coordinate in this vector, so it is a scalar, this is why we do not have underline under beta nor x after the last = sign. Nor objects in equation 6.4

**Comment by CriticalNameError** [comment]
Hello,

thanks for your reply. I do understand that the underline is used to mark vectors. 

So there should be an underline as I porposed.

Please see the screenshot attached:

![error_6 2](https://user-images.githubusercontent.com/38807105/165700027-19a28164-bcd0-49a1-bb85-1c9d924be773.png)
ed.

**Comment by pbiecek** [comment]
@CriticalNameError thank you, 
you are absolutely right,
fixed!
