### ISSUE TITLE
A possible typo in Sec 16.3

### ISSUE THREAD

**Issue by mcavs** [pbiecek/ema#65]
Before Figure 16, there is a statement: "The best result, in terms of the smallest value of  L^0, is obtained for the random forest model (as indicated by the location of the dashed lines in the plots)." I think the best result is obtained for Generalized Boosted Regression in Fig 16.3. 

It may be a typo.

**Comment by pbiecek** [comment]
Thank you, fixed in https://github.com/pbiecek/ema/commit/97b0036335b2be48d27650dd8cee96551f8cf0a2
