### ISSUE TITLE
Question mark instead of dot in the second paragraph of chapter 17.

### ISSUE THREAD

**Issue by Ignaciovf** [pbiecek/ema#67]
Instead of:
_The general idea underlying the construction of PD profiles is to show how does the expected value of model prediction behave as a function of a selected explanatory variable?_ 

It should be:
_The general idea underlying the construction of PD profiles is to show how does the expected value of model prediction behave as a function of a selected explanatory variable._

**Comment by pbiecek** [comment]
@Ignaciovf thank you, it was corrected in 8e256ae852fd05928077ba1339ba8dcfdd2f5cb4
