### ISSUE TITLE
Question about accumulated-local profile

### ISSUE THREAD

**Issue by xiaochi-liu** [pbiecek/ema#68]
Hello, I'm reading chapter 18 "Local-dependence and Accumulated-local Profiles" and found some confusing points。

In section 18.3.3 "Dependence profiles for a model with interaction and correlated explanatory variables: an example", it says

> AL profile shows **the net effect** of  $X^1$ variable.

However, in section 18.5 "Pros and cons", it says:

> When there are interactions in the model, none of the profiles will provide a correct assessment of the effect of any explanatory variable involved in the interaction(s). This is because the profiles for the variable will also include the effect of other variables.

Do these two points sound a little bit contradictory? Is the AL profile suitable for a model with interaction and correlated explanatory variables？

Your kind guidance is much appreciated!

**Comment by pbiecek** [comment]
@xiaochi-liu 
thank you for this great question.

The term net-effect referred to correlation. ALs allow to a large extent to take into account the effect of correlation between variables in determining the effect of a single variable. 
As for correlations, unfortunately, no single profile can show different behavior of a selected variable depending on the interaction. For this you need two-dimensional and higher order profiles.

I will try to clarify this in the text.

**Comment by xiaochi-liu** [comment]
Thank you so much, @pbiecek. Now I have a deeper understanding of ALE!
